UserService:
  url: lb://SecurityMS


General:
  EXCEPTION_MESSAGE: Request could not be processed due to some issue. Please try again!
Service:
  TRANSACTION_NOT_FOUND: Transactions are currently unavailable
resilience4j:
  circuitbreaker:
    instances:
      alltransactionService:
        failure-rate-threshold: 50
        sliding-window-size: 10
        sliding-window-type: count-based
        minimum-number-of-calls: 5
        slowCallDurationThreshold: 3s
        wait-duration-in-open-state: 30s
        automatic-transition-from-open-to-half-open-enabled: true
